const esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const b64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function cls(sev){return sev==='critical'?'critical':sev==='high'?'high':sev==='medium'?'medium':'ok'}
async function decrypt(password,payload){const keyMaterial=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveKey']);const key=await crypto.subtle.deriveKey({name:'PBKDF2',salt:b64(payload.salt),iterations:payload.iterations,hash:'SHA-256'},keyMaterial,{name:'AES-GCM',length:256},false,['decrypt']);const ct=b64(payload.data),tag=b64(payload.tag);const merged=new Uint8Array(ct.length+tag.length);merged.set(ct);merged.set(tag,ct.length);const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64(payload.iv)},key,merged);return JSON.parse(new TextDecoder().decode(raw));}
function render(d){updated.textContent='snapshot '+new Date(d.generatedAt).toLocaleString();gateway.textContent=d.summary.gateway;gateway.className='value '+(d.summary.gateway==='reachable'?'ok':'critical');warnings.textContent=d.summary.openclawWarnings??'n/a';warnings.className='value '+((d.summary.openclawWarnings||0)>0?'medium':'ok');update.textContent=d.summary.updateAvailable?'available':'current';update.className='value '+(d.summary.updateAvailable?'medium':'ok');riskcount.textContent=d.summary.risks;riskcount.className='value '+(d.risks.some(x=>x.severity==='critical')?'critical':d.risks.some(x=>x.severity==='high')?'high':d.risks.length?'medium':'ok');risks.innerHTML=d.risks.length?d.risks.map(x=>'<div class="risk '+esc(x.severity)+'"><b class="'+cls(x.severity)+'">'+esc(x.severity.toUpperCase())+'</b> '+esc(x.name)+'<br><span class="sub">'+esc(x.detail)+'</span></div>').join(''):'<div class="ok">No active dashboard risks.</div>';listeners.textContent=(d.system.keyListeners||[]).join('\n')||'No sensitive key listeners found.';loadbox.textContent=d.system.load||'';disk.textContent=d.system.disk||'';audit.textContent=d.openclaw.audit.raw||'';report.textContent=d.report||'';actions.innerHTML=[['Restrict RDP','High priority. Disable RDP or restrict it to trusted network or tailnet only. Needs Caleb approval.'],['Enable BitLocker','High priority. Turn on disk encryption after recovery key storage is confirmed. Needs Caleb approval.'],['Disable insecure auth flag','High priority if not actively debugging. Keep Control UI local-only either way. Needs Caleb approval.'],['Update OpenClaw','Medium priority. Backup, update to current stable, validate, restart safely, then rerun audit. Needs Caleb approval.'],['Keep Mission Control persistent','Optional. Add startup or cron only after Caleb approves persistence.']].map(([a,b])=>'<div class="check"><div class="medium">●</div><div><strong>'+esc(a)+'</strong><span>'+esc(b)+'</span></div></div>').join('');unlock.classList.add('hidden');app.classList.remove('hidden')}
let payloadPromise=fetch('data.json',{cache:'no-store'}).then(r=>r.json());
form.addEventListener('submit',async e=>{e.preventDefault();msg.textContent='Unlocking...';try{render(await decrypt(password.value,await payloadPromise));msg.textContent=''}catch{msg.textContent='Wrong password or corrupted payload.'}});
document.querySelectorAll('.mobile-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.mobile-tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');cards.className='grid mobile-filter '+btn.dataset.view;}));

